<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page not found</title>
    <style type="text/css">
      body {
        font-family: 游ゴシック, YuGothic, 'ヒラギノ角ゴ Pro W3', 'Hiragino Kaku Gothic Pro', メイリオ, Meiryo, 'ＭＳ Ｐゴシック', 'MS PGothic', sans-serif;
        font-size: 14px;
        margin: 0;
        padding: 0;
        color: #555;
      }
      div, p {
        margin: 0;
        padding: 0;
      }
      a {
        color: #115a97;
      }
      h1 {
        color: #777;
        font-weight: normal;
        border-bottom: solid 1px #888;
        padding-bottom: 15px;
        margin: 0 0 40px;
      }
      .container {
        max-width: 640px;
        margin-left: auto;
        margin-right: auto;
        background-color: #fff;
        padding: 20px;
        height: 470px;
        margin-top: 5%;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Page not found...</h1>
      <a href="javascript: history.back();">Back</a>
    </div>
  </body>
</html>
