<?php
$app = \Slim\Slim::getInstance();
$pattern = $app->router()->getCurrentRoute()->getPattern();
$is_article = ($pattern == '/:y/:m/:d/:t');
?>
  <div class="post">
  <?php if ($post) { ?>
    <h2>
      <?php if ($is_article) { ?>
      <?php echo $post->header->title; ?>
      <?php } else { ?>
      <a href="<?php echo $env['ROOT_PATH'].'/'.$post->id.'.html'; ?>"><?php echo $post->header->title; ?></a>
      <?php } ?>
    </h2>
    
    <div class="post-info">
      written
      by
      <span><?php echo $post->header->author; ?></span>
      at
      <span><?php echo $post->header->created_at; ?></span>
    </div><!-- /post-info -->
    
    <div class="post-contents">
      <?php echo $post->contents; ?>
    </div><!-- /post-contents -->
  <?php } else { ?>
    <?php echo ($body ? $body : ''); ?>
  <?php } ?>
  </div><!-- /post -->
  <a href="<?php echo $env['ROOT_PATH'].'/'.$post->id.'.html'; ?>" class="post-to-post-page">read more</a>
  