        <ol class="breadcrumb">
        <?php foreach($_SESSION['breadcrumbs'] as $row) { ?>
          <?php if (intval($row['id']) == count($_SESSION['breadcrumbs'])) { ?>
          <li class="active"><?php echo $row['text']; ?></a></li>
          <?php } else { ?>
          <li><a href="<?php echo $env['ROOT_PATH'].$row['url']; ?>"><?php echo $row['text']; ?></a></li>
          <?php } ?>
        <?php } ?>
        </ol>
