  <?php if (!empty($env['GOOGLE_CUSTOME_SEARCH_ID'])) { ?>
  <div class="gcse-wrapper">
      <script>
        (function() {
          var cx = '<?php echo $env["GOOGLE_CUSTOME_SEARCH_ID"]; ?>';
          var gcse = document.createElement('script');
          gcse.type = 'text/javascript';
          gcse.async = true;
          gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
              '//cse.google.com/cse.js?cx=' + cx;
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(gcse, s);
        })();
      </script>
      <gcse:search></gcse:search>
    </div><!-- /gcse-wrapper -->
  <?php } ?>