<nav id="header" class="navbar" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <div class="site-info">
        <h1>
          <a href="<?php echo $env['ROOT_PATH']; ?>/index.html" class="navbar-brand"><?php echo $env['SITE_NAME']; ?></a>
        </h1>
        <p class="site-description">
          <?php echo $env['SITE_DESCRIPTION']; ?>
        </p>
      </div>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<?php echo $env['ROOT_PATH']; ?>/index.html">Home</a></li>
        <?php include 'li_link_archives.phtml'; ?>
        <li><a href="<?php echo $env['ROOT_PATH']; ?>/contact.php">Contact</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
