<?php
  if (!isset($header)) $header = array();
  
  $title = $env['SITE_COPY'].' - '.$env['SITE_NAME'];
  $description = $env['SITE_DESCRIPTION'];
  $keywords = $env['SITE_KEYWORDS'];
  
  if (gettype($header) == 'object') {
    if (isset($header->title)) $title = $header->title;
    if (isset($header->description)) $description = $header->description;
    if (isset($header->keywords)) $keywords = $header->keywords;
  } else if (gettype($header) == 'array') {
    if (isset($header['title'])) $title = $header['title'];
    if (isset($header['description'])) $description = $header['description'];
    if (isset($header['keywords'])) $keywords = $header['keywords'];
  }
?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title; ?></title>
    <meta name="description" content="<?php echo $description; ?>">
    <meta name="keywords" content="<?php echo $keywords; ?>">
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js" type="text/javascript"></script>
    <![endif]-->
    
    <link rel="stylesheet" media="all" href="<?php echo $env['ROOT_PATH']; ?>/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" media="all" href="<?php echo $env['ROOT_PATH']; ?>/assets/css/app.css" />
    
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/jquery.min.js"></script>
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/bootstrap.min.js"></script>
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/app.js"></script>
    <?php include 'google_analytics.phtml'; ?>
