<?php
  $title = $env['SITE_COPY'].' - '.$env['SITE_NAME'];
  $description = $env['SITE_DESCRIPTION'];
  $keywords = $env['SITE_KEYWORDS'];
  
  if (isset($header)) {
    $title = $header['title'].' - '.$env['SITE_NAME'];
    $description = $header['description'];
    $keywords = $header['keywords'];
  }
?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title; ?></title>
<?php if (!empty($description)) { ?>
    <meta name="description" content="<?php echo $description; ?>">
<?php } ?>
<?php if (!empty($keywords)) { ?>
    <meta name="keywords" content="<?php echo $keywords; ?>">
<?php } ?>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js" type="text/javascript"></script>
    <![endif]-->
    
    <link rel="stylesheet" media="all" href="<?php echo $env['ROOT_PATH']; ?>/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" media="all" href="<?php echo $env['ROOT_PATH']; ?>/assets/css/app.css" />
    
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/jquery.min.js"></script>
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/bootstrap.min.js"></script>
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/app.js"></script>
    <?php include \Phybrid\PhybridView::include_path('layouts/google_analytics.phtml'); ?>
