<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo (isset($title) ? $title : $env['SITE_COPY']).' - '.$env['SITE_NAME']; ?></title>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js" type="text/javascript"></script>
    <![endif]-->
    
    <link rel="stylesheet" media="all" href="<?php echo $env['ROOT_PATH']; ?>/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" media="all" href="<?php echo $env['ROOT_PATH']; ?>/assets/css/app.css" />
    
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/jquery.min.js"></script>
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/bootstrap.min.js"></script>
    <script src="<?php echo $env['ROOT_PATH']; ?>/assets/js/app.js"></script>
  </head>
  <body>
    <?php include 'header.phtml'; ?>
    
    <div class="contents-wrapper">
      <div class="container">
        <?php include 'breadcrumb.phtml'; ?>
        
        <?php echo $yield; ?>
      </div>
    </div><!-- /.container -->
    
    <?php include 'footer.phtml'; ?>
  </body>
</html>
